### PR TITLE
added logos

### PR DESCRIPTION
**Pull request by ShobhitRathi**
created and added logos for actinoid
includes with
1. **bg**
2. **without bg** 
3. **transparent image** logo

PR for[ issue #1 ](https://github.com/actinoidlabs/actinoid/issues/1)

This is just an alpha design if you want any changes or rework i'm open. Till then you can work around with this

### CODE REVIEW

**Comment by thetinygoat** [comment]
Hi, thanks for the PR, I wanted something minimalistic for the project, I'm sorry I should have mentioned it beforehand. If you have the time I would appreciate it if you could edit them.

**Comment by ShobhitRathi** [comment]
Sure, I'll work on something minimalistic and choose specific colour scheme

**Comment by ShobhitRathi** [comment]
hi, @thetinygoat so you wanted a simplistic logo so I created **2 types** of it you can choose
The logo this time **focuses more on actinoid** and its **brand meaning**.
Tried to keep the logo **minimalistic** and **elegant** and to fit it according to your need

### colour scheme used is: 
#ffffff
#071e2e

**Comment by thetinygoat** [comment]
Thanks for reverting back and the design is minimalistic which is great, but it is not readable as a logo the A in actinoid and not readable. Thank you for your time, I would understand if you don't want to work on this any further. If that's the case I'll close this PR.

**Comment by ShobhitRathi** [comment]
@thetinygoat hey no problem I can just use a regular A in it if you want, is that alright?

**Comment by ShobhitRathi** [comment]
having something is better than having nothing, it would be cool for your project in my opinion

**Comment by thetinygoat** [comment]
Yeah that would be fine, thanks a lot. Try colorizing the parts of the text like [https://github.com/thetinygoat/dotfm](url) and playing around with font style, if that helps.

**Comment by ShobhitRathi** [comment]
@thetinygoat hey so i've looked into your suggestion style and **tried to implement all the ideas you asked for**
The **_logo now has an A instead of memory card_** and **_colour scheme is kept using the simplicity that you asked for_** i.e 
### colour scheme
1. #071e2e (dark blue)
2. #00aacf (light blue/cyan)

For the font style I've kept it to be techy and pop while at the same time being **professional,  elegant** and **minimalistic**
I hope this covers what you need

**Comment by thetinygoat** [comment]
This is perfect, thanks a lot! could you add design files as well for example figma or photoshop files.

**Comment by ShobhitRathi** [comment]
sure

**Comment by ShobhitRathi** [comment]
@thetinygoat added the psd as well you can merge it now

**Pull request merged**
